// Code generated by entc, DO NOT EDIT.

package admindictkey

import (
	"time"
)

const (
	// Label holds the string label denoting the admindictkey type in the database.
	Label = "admin_dict_key"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldDictLabel holds the string denoting the dict_label field in the database.
	FieldDictLabel = "dict_label"
	// FieldDictCode holds the string denoting the dict_code field in the database.
	FieldDictCode = "dict_code"
	// FieldSort holds the string denoting the sort field in the database.
	FieldSort = "sort"
	// FieldRemarks holds the string denoting the remarks field in the database.
	FieldRemarks = "remarks"
	// FieldIsEnable holds the string denoting the is_enable field in the database.
	FieldIsEnable = "is_enable"
	// EdgeP holds the string denoting the p edge name in mutations.
	EdgeP = "P"
	// Table holds the table name of the admindictkey in the database.
	Table = "admin_dict_keys"
	// PTable is the table the holds the P relation/edge.
	PTable = "admin_dict_keys"
	// PInverseTable is the table name for the AdminDict entity.
	// It exists in this package in order to avoid circular dependency with the "admindict" package.
	PInverseTable = "admin_dicts"
	// PColumn is the table column denoting the P relation/edge.
	PColumn = "admin_dict_key"
)

// Columns holds all SQL columns for admindictkey fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldDictLabel,
	FieldDictCode,
	FieldSort,
	FieldRemarks,
	FieldIsEnable,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "admin_dict_keys"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"admin_dict_key",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)
