// Code generated by entc, DO NOT EDIT.

package admindictkey

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/a20070322/go_fast_admin/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.AdminDictKey {
	return predicate.AdminDictKey(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.AdminDictKey {
	return predicate.AdminDictKey(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.AdminDictKey {
	return predicate.AdminDictKey(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.AdminDictKey {
	return predicate.AdminDictKey(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.AdminDictKey {
	return predicate.AdminDictKey(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.AdminDictKey {
	return predicate.AdminDictKey(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.AdminDictKey {
	return predicate.AdminDictKey(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.AdminDictKey {
	return predicate.AdminDictKey(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.AdminDictKey {
	return predicate.AdminDictKey(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AdminDictKey {
	return predicate.AdminDictKey(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCreatedAt), v))
	})
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AdminDictKey {
	return predicate.AdminDictKey(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldUpdatedAt), v))
	})
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.AdminDictKey {
	return predicate.AdminDictKey(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldDeletedAt), v))
	})
}

// DictLabel applies equality check predicate on the "dict_label" field. It's identical to DictLabelEQ.
func DictLabel(v string) predicate.AdminDictKey {
	return predicate.AdminDictKey(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldDictLabel), v))
	})
}

// DictCode applies equality check predicate on the "dict_code" field. It's identical to DictCodeEQ.
func DictCode(v string) predicate.AdminDictKey {
	return predicate.AdminDictKey(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldDictCode), v))
	})
}

// Sort applies equality check predicate on the "sort" field. It's identical to SortEQ.
func Sort(v int) predicate.AdminDictKey {
	return predicate.AdminDictKey(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldSort), v))
	})
}

// Remarks applies equality check predicate on the "remarks" field. It's identical to RemarksEQ.
func Remarks(v string) predicate.AdminDictKey {
	return predicate.AdminDictKey(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldRemarks), v))
	})
}

// IsEnable applies equality check predicate on the "is_enable" field. It's identical to IsEnableEQ.
func IsEnable(v bool) predicate.AdminDictKey {
	return predicate.AdminDictKey(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldIsEnable), v))
	})
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AdminDictKey {
	return predicate.AdminDictKey(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AdminDictKey {
	return predicate.AdminDictKey(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AdminDictKey {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.AdminDictKey(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldCreatedAt), v...))
	})
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AdminDictKey {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.AdminDictKey(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldCreatedAt), v...))
	})
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AdminDictKey {
	return predicate.AdminDictKey(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AdminDictKey {
	return predicate.AdminDictKey(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AdminDictKey {
	return predicate.AdminDictKey(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AdminDictKey {
	return predicate.AdminDictKey(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldCreatedAt), v))
	})
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AdminDictKey {
	return predicate.AdminDictKey(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AdminDictKey {
	return predicate.AdminDictKey(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AdminDictKey {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.AdminDictKey(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldUpdatedAt), v...))
	})
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AdminDictKey {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.AdminDictKey(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldUpdatedAt), v...))
	})
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AdminDictKey {
	return predicate.AdminDictKey(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AdminDictKey {
	return predicate.AdminDictKey(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AdminDictKey {
	return predicate.AdminDictKey(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AdminDictKey {
	return predicate.AdminDictKey(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtIsNil applies the IsNil predicate on the "updated_at" field.
func UpdatedAtIsNil() predicate.AdminDictKey {
	return predicate.AdminDictKey(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldUpdatedAt)))
	})
}

// UpdatedAtNotNil applies the NotNil predicate on the "updated_at" field.
func UpdatedAtNotNil() predicate.AdminDictKey {
	return predicate.AdminDictKey(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldUpdatedAt)))
	})
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.AdminDictKey {
	return predicate.AdminDictKey(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldDeletedAt), v))
	})
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.AdminDictKey {
	return predicate.AdminDictKey(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldDeletedAt), v))
	})
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.AdminDictKey {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.AdminDictKey(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldDeletedAt), v...))
	})
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.AdminDictKey {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.AdminDictKey(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldDeletedAt), v...))
	})
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.AdminDictKey {
	return predicate.AdminDictKey(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldDeletedAt), v))
	})
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.AdminDictKey {
	return predicate.AdminDictKey(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldDeletedAt), v))
	})
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.AdminDictKey {
	return predicate.AdminDictKey(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldDeletedAt), v))
	})
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.AdminDictKey {
	return predicate.AdminDictKey(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldDeletedAt), v))
	})
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.AdminDictKey {
	return predicate.AdminDictKey(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldDeletedAt)))
	})
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.AdminDictKey {
	return predicate.AdminDictKey(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldDeletedAt)))
	})
}

// DictLabelEQ applies the EQ predicate on the "dict_label" field.
func DictLabelEQ(v string) predicate.AdminDictKey {
	return predicate.AdminDictKey(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldDictLabel), v))
	})
}

// DictLabelNEQ applies the NEQ predicate on the "dict_label" field.
func DictLabelNEQ(v string) predicate.AdminDictKey {
	return predicate.AdminDictKey(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldDictLabel), v))
	})
}

// DictLabelIn applies the In predicate on the "dict_label" field.
func DictLabelIn(vs ...string) predicate.AdminDictKey {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.AdminDictKey(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldDictLabel), v...))
	})
}

// DictLabelNotIn applies the NotIn predicate on the "dict_label" field.
func DictLabelNotIn(vs ...string) predicate.AdminDictKey {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.AdminDictKey(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldDictLabel), v...))
	})
}

// DictLabelGT applies the GT predicate on the "dict_label" field.
func DictLabelGT(v string) predicate.AdminDictKey {
	return predicate.AdminDictKey(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldDictLabel), v))
	})
}

// DictLabelGTE applies the GTE predicate on the "dict_label" field.
func DictLabelGTE(v string) predicate.AdminDictKey {
	return predicate.AdminDictKey(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldDictLabel), v))
	})
}

// DictLabelLT applies the LT predicate on the "dict_label" field.
func DictLabelLT(v string) predicate.AdminDictKey {
	return predicate.AdminDictKey(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldDictLabel), v))
	})
}

// DictLabelLTE applies the LTE predicate on the "dict_label" field.
func DictLabelLTE(v string) predicate.AdminDictKey {
	return predicate.AdminDictKey(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldDictLabel), v))
	})
}

// DictLabelContains applies the Contains predicate on the "dict_label" field.
func DictLabelContains(v string) predicate.AdminDictKey {
	return predicate.AdminDictKey(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldDictLabel), v))
	})
}

// DictLabelHasPrefix applies the HasPrefix predicate on the "dict_label" field.
func DictLabelHasPrefix(v string) predicate.AdminDictKey {
	return predicate.AdminDictKey(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldDictLabel), v))
	})
}

// DictLabelHasSuffix applies the HasSuffix predicate on the "dict_label" field.
func DictLabelHasSuffix(v string) predicate.AdminDictKey {
	return predicate.AdminDictKey(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldDictLabel), v))
	})
}

// DictLabelEqualFold applies the EqualFold predicate on the "dict_label" field.
func DictLabelEqualFold(v string) predicate.AdminDictKey {
	return predicate.AdminDictKey(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldDictLabel), v))
	})
}

// DictLabelContainsFold applies the ContainsFold predicate on the "dict_label" field.
func DictLabelContainsFold(v string) predicate.AdminDictKey {
	return predicate.AdminDictKey(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldDictLabel), v))
	})
}

// DictCodeEQ applies the EQ predicate on the "dict_code" field.
func DictCodeEQ(v string) predicate.AdminDictKey {
	return predicate.AdminDictKey(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldDictCode), v))
	})
}

// DictCodeNEQ applies the NEQ predicate on the "dict_code" field.
func DictCodeNEQ(v string) predicate.AdminDictKey {
	return predicate.AdminDictKey(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldDictCode), v))
	})
}

// DictCodeIn applies the In predicate on the "dict_code" field.
func DictCodeIn(vs ...string) predicate.AdminDictKey {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.AdminDictKey(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldDictCode), v...))
	})
}

// DictCodeNotIn applies the NotIn predicate on the "dict_code" field.
func DictCodeNotIn(vs ...string) predicate.AdminDictKey {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.AdminDictKey(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldDictCode), v...))
	})
}

// DictCodeGT applies the GT predicate on the "dict_code" field.
func DictCodeGT(v string) predicate.AdminDictKey {
	return predicate.AdminDictKey(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldDictCode), v))
	})
}

// DictCodeGTE applies the GTE predicate on the "dict_code" field.
func DictCodeGTE(v string) predicate.AdminDictKey {
	return predicate.AdminDictKey(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldDictCode), v))
	})
}

// DictCodeLT applies the LT predicate on the "dict_code" field.
func DictCodeLT(v string) predicate.AdminDictKey {
	return predicate.AdminDictKey(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldDictCode), v))
	})
}

// DictCodeLTE applies the LTE predicate on the "dict_code" field.
func DictCodeLTE(v string) predicate.AdminDictKey {
	return predicate.AdminDictKey(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldDictCode), v))
	})
}

// DictCodeContains applies the Contains predicate on the "dict_code" field.
func DictCodeContains(v string) predicate.AdminDictKey {
	return predicate.AdminDictKey(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldDictCode), v))
	})
}

// DictCodeHasPrefix applies the HasPrefix predicate on the "dict_code" field.
func DictCodeHasPrefix(v string) predicate.AdminDictKey {
	return predicate.AdminDictKey(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldDictCode), v))
	})
}

// DictCodeHasSuffix applies the HasSuffix predicate on the "dict_code" field.
func DictCodeHasSuffix(v string) predicate.AdminDictKey {
	return predicate.AdminDictKey(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldDictCode), v))
	})
}

// DictCodeEqualFold applies the EqualFold predicate on the "dict_code" field.
func DictCodeEqualFold(v string) predicate.AdminDictKey {
	return predicate.AdminDictKey(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldDictCode), v))
	})
}

// DictCodeContainsFold applies the ContainsFold predicate on the "dict_code" field.
func DictCodeContainsFold(v string) predicate.AdminDictKey {
	return predicate.AdminDictKey(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldDictCode), v))
	})
}

// SortEQ applies the EQ predicate on the "sort" field.
func SortEQ(v int) predicate.AdminDictKey {
	return predicate.AdminDictKey(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldSort), v))
	})
}

// SortNEQ applies the NEQ predicate on the "sort" field.
func SortNEQ(v int) predicate.AdminDictKey {
	return predicate.AdminDictKey(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldSort), v))
	})
}

// SortIn applies the In predicate on the "sort" field.
func SortIn(vs ...int) predicate.AdminDictKey {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.AdminDictKey(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldSort), v...))
	})
}

// SortNotIn applies the NotIn predicate on the "sort" field.
func SortNotIn(vs ...int) predicate.AdminDictKey {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.AdminDictKey(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldSort), v...))
	})
}

// SortGT applies the GT predicate on the "sort" field.
func SortGT(v int) predicate.AdminDictKey {
	return predicate.AdminDictKey(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldSort), v))
	})
}

// SortGTE applies the GTE predicate on the "sort" field.
func SortGTE(v int) predicate.AdminDictKey {
	return predicate.AdminDictKey(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldSort), v))
	})
}

// SortLT applies the LT predicate on the "sort" field.
func SortLT(v int) predicate.AdminDictKey {
	return predicate.AdminDictKey(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldSort), v))
	})
}

// SortLTE applies the LTE predicate on the "sort" field.
func SortLTE(v int) predicate.AdminDictKey {
	return predicate.AdminDictKey(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldSort), v))
	})
}

// SortIsNil applies the IsNil predicate on the "sort" field.
func SortIsNil() predicate.AdminDictKey {
	return predicate.AdminDictKey(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldSort)))
	})
}

// SortNotNil applies the NotNil predicate on the "sort" field.
func SortNotNil() predicate.AdminDictKey {
	return predicate.AdminDictKey(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldSort)))
	})
}

// RemarksEQ applies the EQ predicate on the "remarks" field.
func RemarksEQ(v string) predicate.AdminDictKey {
	return predicate.AdminDictKey(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldRemarks), v))
	})
}

// RemarksNEQ applies the NEQ predicate on the "remarks" field.
func RemarksNEQ(v string) predicate.AdminDictKey {
	return predicate.AdminDictKey(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldRemarks), v))
	})
}

// RemarksIn applies the In predicate on the "remarks" field.
func RemarksIn(vs ...string) predicate.AdminDictKey {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.AdminDictKey(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldRemarks), v...))
	})
}

// RemarksNotIn applies the NotIn predicate on the "remarks" field.
func RemarksNotIn(vs ...string) predicate.AdminDictKey {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.AdminDictKey(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldRemarks), v...))
	})
}

// RemarksGT applies the GT predicate on the "remarks" field.
func RemarksGT(v string) predicate.AdminDictKey {
	return predicate.AdminDictKey(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldRemarks), v))
	})
}

// RemarksGTE applies the GTE predicate on the "remarks" field.
func RemarksGTE(v string) predicate.AdminDictKey {
	return predicate.AdminDictKey(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldRemarks), v))
	})
}

// RemarksLT applies the LT predicate on the "remarks" field.
func RemarksLT(v string) predicate.AdminDictKey {
	return predicate.AdminDictKey(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldRemarks), v))
	})
}

// RemarksLTE applies the LTE predicate on the "remarks" field.
func RemarksLTE(v string) predicate.AdminDictKey {
	return predicate.AdminDictKey(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldRemarks), v))
	})
}

// RemarksContains applies the Contains predicate on the "remarks" field.
func RemarksContains(v string) predicate.AdminDictKey {
	return predicate.AdminDictKey(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldRemarks), v))
	})
}

// RemarksHasPrefix applies the HasPrefix predicate on the "remarks" field.
func RemarksHasPrefix(v string) predicate.AdminDictKey {
	return predicate.AdminDictKey(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldRemarks), v))
	})
}

// RemarksHasSuffix applies the HasSuffix predicate on the "remarks" field.
func RemarksHasSuffix(v string) predicate.AdminDictKey {
	return predicate.AdminDictKey(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldRemarks), v))
	})
}

// RemarksIsNil applies the IsNil predicate on the "remarks" field.
func RemarksIsNil() predicate.AdminDictKey {
	return predicate.AdminDictKey(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldRemarks)))
	})
}

// RemarksNotNil applies the NotNil predicate on the "remarks" field.
func RemarksNotNil() predicate.AdminDictKey {
	return predicate.AdminDictKey(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldRemarks)))
	})
}

// RemarksEqualFold applies the EqualFold predicate on the "remarks" field.
func RemarksEqualFold(v string) predicate.AdminDictKey {
	return predicate.AdminDictKey(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldRemarks), v))
	})
}

// RemarksContainsFold applies the ContainsFold predicate on the "remarks" field.
func RemarksContainsFold(v string) predicate.AdminDictKey {
	return predicate.AdminDictKey(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldRemarks), v))
	})
}

// IsEnableEQ applies the EQ predicate on the "is_enable" field.
func IsEnableEQ(v bool) predicate.AdminDictKey {
	return predicate.AdminDictKey(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldIsEnable), v))
	})
}

// IsEnableNEQ applies the NEQ predicate on the "is_enable" field.
func IsEnableNEQ(v bool) predicate.AdminDictKey {
	return predicate.AdminDictKey(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldIsEnable), v))
	})
}

// HasP applies the HasEdge predicate on the "P" edge.
func HasP() predicate.AdminDictKey {
	return predicate.AdminDictKey(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(PTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PTable, PColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPWith applies the HasEdge predicate on the "P" edge with a given conditions (other predicates).
func HasPWith(preds ...predicate.AdminDict) predicate.AdminDictKey {
	return predicate.AdminDictKey(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(PInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PTable, PColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AdminDictKey) predicate.AdminDictKey {
	return predicate.AdminDictKey(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AdminDictKey) predicate.AdminDictKey {
	return predicate.AdminDictKey(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AdminDictKey) predicate.AdminDictKey {
	return predicate.AdminDictKey(func(s *sql.Selector) {
		p(s.Not())
	})
}
