// Code generated by entc, DO NOT EDIT.

package adminmenus

import (
	"time"
)

const (
	// Label holds the string label denoting the adminmenus type in the database.
	Label = "admin_menus"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldPath holds the string denoting the path field in the database.
	FieldPath = "path"
	// FieldPathAction holds the string denoting the path_action field in the database.
	FieldPathAction = "path_action"
	// FieldRouterPath holds the string denoting the router_path field in the database.
	FieldRouterPath = "router_path"
	// FieldIcon holds the string denoting the icon field in the database.
	FieldIcon = "icon"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldPowerStr holds the string denoting the power_str field in the database.
	FieldPowerStr = "power_str"
	// FieldSort holds the string denoting the sort field in the database.
	FieldSort = "sort"
	// FieldFid holds the string denoting the fid field in the database.
	FieldFid = "fid"
	// FieldIsExternalLink holds the string denoting the is_external_link field in the database.
	FieldIsExternalLink = "is_external_link"
	// FieldIsShow holds the string denoting the is_show field in the database.
	FieldIsShow = "is_show"
	// FieldIsEnable holds the string denoting the is_enable field in the database.
	FieldIsEnable = "is_enable"
	// EdgeRole holds the string denoting the role edge name in mutations.
	EdgeRole = "role"
	// Table holds the table name of the adminmenus in the database.
	Table = "admin_menus"
	// RoleTable is the table the holds the role relation/edge. The primary key declared below.
	RoleTable = "admin_role_menu"
	// RoleInverseTable is the table name for the AdminRole entity.
	// It exists in this package in order to avoid circular dependency with the "adminrole" package.
	RoleInverseTable = "admin_roles"
)

// Columns holds all SQL columns for adminmenus fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldName,
	FieldPath,
	FieldPathAction,
	FieldRouterPath,
	FieldIcon,
	FieldType,
	FieldPowerStr,
	FieldSort,
	FieldFid,
	FieldIsExternalLink,
	FieldIsShow,
	FieldIsEnable,
}

var (
	// RolePrimaryKey and RoleColumn2 are the table columns denoting the
	// primary key for the role relation (M2M).
	RolePrimaryKey = []string{"admin_role_id", "admin_menus_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultIcon holds the default value on creation for the "icon" field.
	DefaultIcon string
	// DefaultType holds the default value on creation for the "type" field.
	DefaultType int8
	// DefaultSort holds the default value on creation for the "sort" field.
	DefaultSort int
	// SortValidator is a validator for the "sort" field. It is called by the builders before save.
	SortValidator func(int) error
	// DefaultIsExternalLink holds the default value on creation for the "is_external_link" field.
	DefaultIsExternalLink bool
	// DefaultIsShow holds the default value on creation for the "is_show" field.
	DefaultIsShow bool
	// DefaultIsEnable holds the default value on creation for the "is_enable" field.
	DefaultIsEnable bool
)
