// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/a20070322/go_fast_admin/ent/adminmenus"
	"github.com/a20070322/go_fast_admin/ent/predicate"
)

// AdminMenusDelete is the builder for deleting a AdminMenus entity.
type AdminMenusDelete struct {
	config
	hooks    []Hook
	mutation *AdminMenusMutation
}

// Where adds a new predicate to the AdminMenusDelete builder.
func (amd *AdminMenusDelete) Where(ps ...predicate.AdminMenus) *AdminMenusDelete {
	amd.mutation.predicates = append(amd.mutation.predicates, ps...)
	return amd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (amd *AdminMenusDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(amd.hooks) == 0 {
		affected, err = amd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*AdminMenusMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			amd.mutation = mutation
			affected, err = amd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(amd.hooks) - 1; i >= 0; i-- {
			mut = amd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, amd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (amd *AdminMenusDelete) ExecX(ctx context.Context) int {
	n, err := amd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (amd *AdminMenusDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: adminmenus.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: adminmenus.FieldID,
			},
		},
	}
	if ps := amd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, amd.driver, _spec)
}

// AdminMenusDeleteOne is the builder for deleting a single AdminMenus entity.
type AdminMenusDeleteOne struct {
	amd *AdminMenusDelete
}

// Exec executes the deletion query.
func (amdo *AdminMenusDeleteOne) Exec(ctx context.Context) error {
	n, err := amdo.amd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{adminmenus.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (amdo *AdminMenusDeleteOne) ExecX(ctx context.Context) {
	amdo.amd.ExecX(ctx)
}
