// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/a20070322/go_fast_admin/ent/admindictkey"
	"github.com/a20070322/go_fast_admin/ent/predicate"
)

// AdminDictKeyDelete is the builder for deleting a AdminDictKey entity.
type AdminDictKeyDelete struct {
	config
	hooks    []Hook
	mutation *AdminDictKeyMutation
}

// Where adds a new predicate to the AdminDictKeyDelete builder.
func (adkd *AdminDictKeyDelete) Where(ps ...predicate.AdminDictKey) *AdminDictKeyDelete {
	adkd.mutation.predicates = append(adkd.mutation.predicates, ps...)
	return adkd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (adkd *AdminDictKeyDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(adkd.hooks) == 0 {
		affected, err = adkd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*AdminDictKeyMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			adkd.mutation = mutation
			affected, err = adkd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(adkd.hooks) - 1; i >= 0; i-- {
			mut = adkd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, adkd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (adkd *AdminDictKeyDelete) ExecX(ctx context.Context) int {
	n, err := adkd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (adkd *AdminDictKeyDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: admindictkey.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: admindictkey.FieldID,
			},
		},
	}
	if ps := adkd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, adkd.driver, _spec)
}

// AdminDictKeyDeleteOne is the builder for deleting a single AdminDictKey entity.
type AdminDictKeyDeleteOne struct {
	adkd *AdminDictKeyDelete
}

// Exec executes the deletion query.
func (adkdo *AdminDictKeyDeleteOne) Exec(ctx context.Context) error {
	n, err := adkdo.adkd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{admindictkey.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (adkdo *AdminDictKeyDeleteOne) ExecX(ctx context.Context) {
	adkdo.adkd.ExecX(ctx)
}
