// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/a20070322/go_fast_admin/ent/admindict"
	"github.com/a20070322/go_fast_admin/ent/predicate"
)

// AdminDictDelete is the builder for deleting a AdminDict entity.
type AdminDictDelete struct {
	config
	hooks    []Hook
	mutation *AdminDictMutation
}

// Where adds a new predicate to the AdminDictDelete builder.
func (add *AdminDictDelete) Where(ps ...predicate.AdminDict) *AdminDictDelete {
	add.mutation.predicates = append(add.mutation.predicates, ps...)
	return add
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (add *AdminDictDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(add.hooks) == 0 {
		affected, err = add.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*AdminDictMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			add.mutation = mutation
			affected, err = add.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(add.hooks) - 1; i >= 0; i-- {
			mut = add.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, add.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (add *AdminDictDelete) ExecX(ctx context.Context) int {
	n, err := add.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (add *AdminDictDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: admindict.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: admindict.FieldID,
			},
		},
	}
	if ps := add.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, add.driver, _spec)
}

// AdminDictDeleteOne is the builder for deleting a single AdminDict entity.
type AdminDictDeleteOne struct {
	add *AdminDictDelete
}

// Exec executes the deletion query.
func (addo *AdminDictDeleteOne) Exec(ctx context.Context) error {
	n, err := addo.add.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{admindict.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (addo *AdminDictDeleteOne) ExecX(ctx context.Context) {
	addo.add.ExecX(ctx)
}
