// Code generated by entc, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/a20070322/go_fast_admin/ent/admindict"
	"github.com/a20070322/go_fast_admin/ent/admindictkey"
	"github.com/a20070322/go_fast_admin/ent/adminmenus"
	"github.com/a20070322/go_fast_admin/ent/adminrole"
	"github.com/a20070322/go_fast_admin/ent/adminuser"
	"github.com/a20070322/go_fast_admin/ent/schema"
	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	admindictMixin := schema.AdminDict{}.Mixin()
	admindictMixinFields0 := admindictMixin[0].Fields()
	_ = admindictMixinFields0
	admindictFields := schema.AdminDict{}.Fields()
	_ = admindictFields
	// admindictDescCreatedAt is the schema descriptor for created_at field.
	admindictDescCreatedAt := admindictMixinFields0[0].Descriptor()
	// admindict.DefaultCreatedAt holds the default value on creation for the created_at field.
	admindict.DefaultCreatedAt = admindictDescCreatedAt.Default.(func() time.Time)
	// admindictDescUpdatedAt is the schema descriptor for updated_at field.
	admindictDescUpdatedAt := admindictMixinFields0[1].Descriptor()
	// admindict.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	admindict.UpdateDefaultUpdatedAt = admindictDescUpdatedAt.UpdateDefault.(func() time.Time)
	admindictkeyMixin := schema.AdminDictKey{}.Mixin()
	admindictkeyMixinFields0 := admindictkeyMixin[0].Fields()
	_ = admindictkeyMixinFields0
	admindictkeyFields := schema.AdminDictKey{}.Fields()
	_ = admindictkeyFields
	// admindictkeyDescCreatedAt is the schema descriptor for created_at field.
	admindictkeyDescCreatedAt := admindictkeyMixinFields0[0].Descriptor()
	// admindictkey.DefaultCreatedAt holds the default value on creation for the created_at field.
	admindictkey.DefaultCreatedAt = admindictkeyDescCreatedAt.Default.(func() time.Time)
	// admindictkeyDescUpdatedAt is the schema descriptor for updated_at field.
	admindictkeyDescUpdatedAt := admindictkeyMixinFields0[1].Descriptor()
	// admindictkey.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	admindictkey.UpdateDefaultUpdatedAt = admindictkeyDescUpdatedAt.UpdateDefault.(func() time.Time)
	adminmenusMixin := schema.AdminMenus{}.Mixin()
	adminmenusMixinFields0 := adminmenusMixin[0].Fields()
	_ = adminmenusMixinFields0
	adminmenusFields := schema.AdminMenus{}.Fields()
	_ = adminmenusFields
	// adminmenusDescCreatedAt is the schema descriptor for created_at field.
	adminmenusDescCreatedAt := adminmenusMixinFields0[0].Descriptor()
	// adminmenus.DefaultCreatedAt holds the default value on creation for the created_at field.
	adminmenus.DefaultCreatedAt = adminmenusDescCreatedAt.Default.(func() time.Time)
	// adminmenusDescUpdatedAt is the schema descriptor for updated_at field.
	adminmenusDescUpdatedAt := adminmenusMixinFields0[1].Descriptor()
	// adminmenus.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	adminmenus.UpdateDefaultUpdatedAt = adminmenusDescUpdatedAt.UpdateDefault.(func() time.Time)
	// adminmenusDescIcon is the schema descriptor for icon field.
	adminmenusDescIcon := adminmenusFields[4].Descriptor()
	// adminmenus.DefaultIcon holds the default value on creation for the icon field.
	adminmenus.DefaultIcon = adminmenusDescIcon.Default.(string)
	// adminmenusDescType is the schema descriptor for type field.
	adminmenusDescType := adminmenusFields[5].Descriptor()
	// adminmenus.DefaultType holds the default value on creation for the type field.
	adminmenus.DefaultType = adminmenusDescType.Default.(int8)
	// adminmenusDescSort is the schema descriptor for sort field.
	adminmenusDescSort := adminmenusFields[7].Descriptor()
	// adminmenus.DefaultSort holds the default value on creation for the sort field.
	adminmenus.DefaultSort = adminmenusDescSort.Default.(int)
	// adminmenus.SortValidator is a validator for the "sort" field. It is called by the builders before save.
	adminmenus.SortValidator = adminmenusDescSort.Validators[0].(func(int) error)
	// adminmenusDescIsExternalLink is the schema descriptor for is_external_link field.
	adminmenusDescIsExternalLink := adminmenusFields[9].Descriptor()
	// adminmenus.DefaultIsExternalLink holds the default value on creation for the is_external_link field.
	adminmenus.DefaultIsExternalLink = adminmenusDescIsExternalLink.Default.(bool)
	// adminmenusDescIsShow is the schema descriptor for is_show field.
	adminmenusDescIsShow := adminmenusFields[10].Descriptor()
	// adminmenus.DefaultIsShow holds the default value on creation for the is_show field.
	adminmenus.DefaultIsShow = adminmenusDescIsShow.Default.(bool)
	// adminmenusDescIsEnable is the schema descriptor for is_enable field.
	adminmenusDescIsEnable := adminmenusFields[11].Descriptor()
	// adminmenus.DefaultIsEnable holds the default value on creation for the is_enable field.
	adminmenus.DefaultIsEnable = adminmenusDescIsEnable.Default.(bool)
	adminroleMixin := schema.AdminRole{}.Mixin()
	adminroleMixinFields0 := adminroleMixin[0].Fields()
	_ = adminroleMixinFields0
	adminroleFields := schema.AdminRole{}.Fields()
	_ = adminroleFields
	// adminroleDescCreatedAt is the schema descriptor for created_at field.
	adminroleDescCreatedAt := adminroleMixinFields0[0].Descriptor()
	// adminrole.DefaultCreatedAt holds the default value on creation for the created_at field.
	adminrole.DefaultCreatedAt = adminroleDescCreatedAt.Default.(func() time.Time)
	// adminroleDescUpdatedAt is the schema descriptor for updated_at field.
	adminroleDescUpdatedAt := adminroleMixinFields0[1].Descriptor()
	// adminrole.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	adminrole.UpdateDefaultUpdatedAt = adminroleDescUpdatedAt.UpdateDefault.(func() time.Time)
	// adminroleDescIsEnable is the schema descriptor for is_enable field.
	adminroleDescIsEnable := adminroleFields[1].Descriptor()
	// adminrole.DefaultIsEnable holds the default value on creation for the is_enable field.
	adminrole.DefaultIsEnable = adminroleDescIsEnable.Default.(bool)
	adminuserMixin := schema.AdminUser{}.Mixin()
	adminuserMixinFields0 := adminuserMixin[0].Fields()
	_ = adminuserMixinFields0
	adminuserFields := schema.AdminUser{}.Fields()
	_ = adminuserFields
	// adminuserDescCreatedAt is the schema descriptor for created_at field.
	adminuserDescCreatedAt := adminuserMixinFields0[0].Descriptor()
	// adminuser.DefaultCreatedAt holds the default value on creation for the created_at field.
	adminuser.DefaultCreatedAt = adminuserDescCreatedAt.Default.(func() time.Time)
	// adminuserDescUpdatedAt is the schema descriptor for updated_at field.
	adminuserDescUpdatedAt := adminuserMixinFields0[1].Descriptor()
	// adminuser.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	adminuser.UpdateDefaultUpdatedAt = adminuserDescUpdatedAt.UpdateDefault.(func() time.Time)
	// adminuserDescIsEnable is the schema descriptor for is_enable field.
	adminuserDescIsEnable := adminuserFields[5].Descriptor()
	// adminuser.DefaultIsEnable holds the default value on creation for the is_enable field.
	adminuser.DefaultIsEnable = adminuserDescIsEnable.Default.(bool)
	// adminuserDescID is the schema descriptor for id field.
	adminuserDescID := adminuserFields[0].Descriptor()
	// adminuser.DefaultID holds the default value on creation for the id field.
	adminuser.DefaultID = adminuserDescID.Default.(func() uuid.UUID)
}
