// Code generated by entc, DO NOT EDIT.

package autouserexample

import (
	"time"
)

const (
	// Label holds the string label denoting the autouserexample type in the database.
	Label = "auto_user_example"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldTestText holds the string denoting the test_text field in the database.
	FieldTestText = "test_text"
	// FieldTestBool holds the string denoting the test_bool field in the database.
	FieldTestBool = "test_bool"
	// FieldTestInt holds the string denoting the test_int field in the database.
	FieldTestInt = "test_int"
	// Table holds the table name of the autouserexample in the database.
	Table = "auto_user_examples"
)

// Columns holds all SQL columns for autouserexample fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldTestText,
	FieldTestBool,
	FieldTestInt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultTestText holds the default value on creation for the "test_text" field.
	DefaultTestText string
	// DefaultTestBool holds the default value on creation for the "test_bool" field.
	DefaultTestBool bool
)
