// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AdminDict is the predicate function for admindict builders.
type AdminDict func(*sql.Selector)

// AdminDictKey is the predicate function for admindictkey builders.
type AdminDictKey func(*sql.Selector)

// AdminMenus is the predicate function for adminmenus builders.
type AdminMenus func(*sql.Selector)

// AdminRole is the predicate function for adminrole builders.
type AdminRole func(*sql.Selector)

// AdminUser is the predicate function for adminuser builders.
type AdminUser func(*sql.Selector)

// AutoUserExample is the predicate function for autouserexample builders.
type AutoUserExample func(*sql.Selector)
