// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AdminMenus is the predicate function for adminmenus builders.
type AdminMenus func(*sql.Selector)

// AdminRole is the predicate function for adminrole builders.
type AdminRole func(*sql.Selector)

// AdminUser is the predicate function for adminuser builders.
type AdminUser func(*sql.Selector)

// CasbinRules is the predicate function for casbinrules builders.
type CasbinRules func(*sql.Selector)
